openapi: '3.0.3'
info:
  title: STD23025 - TD1
  version: '1.0.0'
servers:
  - url: https://localhost.std23025.com
paths:
  /customers:
    get:
      responses:
        '200':
          description: TD
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/shemas/Customer"

components:
  schemas:
    /customers:
      type: ogject
      propreties:
      name:
        type: string
      age:
        type: integer